
--1. Display the Department id, name and id and the name of its manager

select Dnum,Dname,MGRSSN, Fname +' '+Lname as FullName
from Departments dept inner join Employee emp
on emp.SSN=dept.MGRSSN

--2. Display the name of the departments and the name of the projects under its control

select dept.Dname,proj.Pname
from Departments dept inner join Project proj
on dept.Dnum = proj.Dnum

--3. Display the full data about all the dependence associated with the name of the employee they depend on him/her.select depend.*, Fname +' '+Lname as FullNamefrom Employee emp inner join Dependent dependon emp.SSN=depend.ESSN--4. Display the Id, name and location of the projects in Cairo or Alex city.select Pnumber,Pname,Plocationfrom Projectwhere City in('Alex','Cairo')--5. Display the Projects full data of the projects with a name starts with "a" letter.select *from Projectwhere Pname like 'a%'--6. display all the employees in department 30 whose salary from 1000 to 2000 LE monthlyselect * from Employeewhere Dno=30 and Salary between 1000 and 2000--7. Retrieve the names of all employees in department 10 who works more than or equal10 hours per week on "AL Rabwah" project.select Fname +' '+Lname as FullNamefrom Employee emp inner join Works_for workon emp.SSN =work.ESSn and Dno=10 and Hours>=10inner join Project proj on work.Pno = proj.Pnumber and proj.Pname='AL Rabwah'--8. Find the names of the employees who directly supervised with Kamel Mohamedselect  emp.Fname +' '+emp.Lname as FullNamefrom Employee super inner join Employee empon super.SSN = emp.Superssn and  super.Fname +' '+super.Lname ='Kamel Mohamed'--9. Retrieve the names of all employees and the names of the projects they are working on, sorted by the project name.select emp.Fname +' '+emp.Lname as [Employee FullName],proj.Pname  from Employee emp inner join Works_for workon emp.SSN =work.ESSninner join Project projon work.Pno = proj.Pnumberorder by proj.Pname--10. For each project located in Cairo City , find the project number, the controlling department name ,the department manager last name ,address and birthdate.select proj.Pname,proj.Pnumber,emp.Lname,emp.Address,emp.Bdatefrom Project proj inner join Departments depton dept.Dnum = proj.Dnum and proj.City ='Cairo'inner join Employee emp on emp.SSN = dept.MGRSSN--11. Display All Data of the mangersselect distinct  emp.*from Departments dept inner join Employee empon emp.SSN =dept.MGRSSN--12. Display All Employees data and the data of their dependents even if they have no dependentsselect emp.*,depend.*from Employee emp left outer join Dependent dependon emp.SSN = depend.ESSN--13. Insert your personal data to the employee table as a new employee in department number 30, SSN = 102672, Superssn = 112233, salary=3000insert into Employee(Fname,Lname,SSN,Bdate,Address,Sex,Salary,Superssn,Dno)values('mahmoud','shawky',102672,'11-5-2002','cairo','m',3000,112233,30)--14. Insert another employee with personal data your friend as new employee in department number 30, SSN = 102660, but don’t enter any value for salary or manager number to himinsert into Employee(Fname,Lname,SSN,Bdate,Address,Sex,Dno)values('ali','amr',102660,'3-3-2004','alex','m',30)--15. Upgrade your salary by 20 % of its last valueupdate Employeeset Salary +=(Salary*.2)where SSN = 102672